### ISSUE TITLE
[BUG] dcgm label的逻辑有误&有些不支持的指标&缺少一些meta label

### ISSUE THREAD

**Issue by Wangyiwei-So** [zjnc-tech/vector#12]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### 问题描述

存在不支持的指标：

```shell
2025-06-24T04:32:48.401858Z  INFO source{component_kind="source" component_id=aggregator_source component_type=vector}: vector::sources::util::grpc: Building gRPC server. address=0.0.0.0:6000
Failed to collect field 230 for GPU 0: dcgm_ret = 0, field_status = -14
Failed to collect field 449 for GPU 0: dcgm_ret = 0, field_status = -6
Failed to collect field 230 for GPU 1: dcgm_ret = 0, field_status = -14
Failed to collect field 449 for GPU 1: dcgm_ret = 0, field_status = -6
Failed to collect field 230 for GPU 2: dcgm_ret = 0, field_status = -14
Failed to collect field 449 for GPU 2: dcgm_ret = 0, field_status = -6
Failed to collect field 230 for GPU 3: dcgm_ret = 0, field_status = -14
Failed to collect field 449 for GPU 3: dcgm_ret = 0, field_status = -6
```

我的配置:
```yaml
dcgm:
        type: dcgm
        groups:
          high:
            scrape_interval_secs: 5
            fields: [
              # DCP metrics
              # DCGM_FI_PROF_GR_ENGINE_ACTIVE,   #gauge, Ratio of time the graphics engine is active (in %).
              DCGM_FI_PROF_SM_ACTIVE,          #gauge, The ratio of cycles an SM has at least 1 warp assigned (in %).
              DCGM_FI_PROF_SM_OCCUPANCY,       #gauge, The ratio of number of warps resident on an SM (in %).
              DCGM_FI_PROF_PIPE_TENSOR_ACTIVE, #gauge, Ratio of cycles the tensor (HMMA) pipe is active (in %).
              DCGM_FI_PROF_DRAM_ACTIVE,        #gauge, Ratio of cycles the device memory interface is active sending or receiving data (in %).
              DCGM_FI_PROF_PIPE_FP64_ACTIVE,   #gauge, Ratio of cycles the fp64 pipes are active (in %).
              DCGM_FI_PROF_PIPE_FP32_ACTIVE,   #gauge, Ratio of cycles the fp32 pipes are active (in %).
              DCGM_FI_PROF_PIPE_FP16_ACTIVE,   #gauge, Ratio of cycles the fp16 pipes are active (in %).
              DCGM_FI_PROF_PCIE_TX_BYTES,      #gauge, The rate of data transmitted over the PCIe bus - including both protocol headers and data payloads - in bytes per second.
              DCGM_FI_PROF_PCIE_RX_BYTES,      #gauge, The rate of data received over the PCIe bus - including both protocol headers and data payloads - in bytes per second.
              DCGM_FI_PROF_NVLINK_RX_BYTES,    #gauge, The rate of data transmitted over the NvLink bus - including both protocol headers and data payloads - in bytes per second.
              DCGM_FI_PROF_NVLINK_TX_BYTES,    #gauge, The rate of data received over the NvLink bus - including both protocol headers and data payloads - in bytes per second.
            ]
          mid:
            scrape_interval_secs: 60
            fields: [
              # Temperature
              DCGM_FI_DEV_MEMORY_TEMP, #gauge, Memory temperature (in C).
              DCGM_FI_DEV_GPU_TEMP,    #gauge, GPU temperature (in C).

              # Power
              DCGM_FI_DEV_POWER_USAGE,              #gauge, Power draw (in W).
              DCGM_FI_DEV_POWER_MGMT_LIMIT,         #gauge, Power limit (in W).
              DCGM_FI_DEV_TOTAL_ENERGY_CONSUMPTION, #counter, Total energy consumption since boot (in mJ).

              # PCIE
              # DCGM_FI_DEV_PCIE_TX_THROUGHPUT,  #counter, Total number of bytes transmitted through PCIe TX (in KB) via NVML.
              # DCGM_FI_DEV_PCIE_RX_THROUGHPUT,  #counter, Total number of bytes received through PCIe RX (in KB) via NVML.
              # DCGM_FI_DEV_PCIE_REPLAY_COUNTER, #counter, Total number of PCIe retries.

              # Utilization (the sample period varies depending on the product)
              DCGM_FI_DEV_GPU_UTIL,      #gauge, GPU utilization (in %).
              DCGM_FI_DEV_MEM_COPY_UTIL, #gauge, Memory utilization (in %).
              DCGM_FI_DEV_ENC_UTIL,      #gauge, Encoder utilization (in %).
              DCGM_FI_DEV_DEC_UTIL ,     #gauge, Decoder utilization (in %).

              # Errors and violations
              DCGM_FI_DEV_XID_ERRORS,            #gauge,   Value of the last XID error encountered.
              DCGM_FI_DEV_POWER_VIOLATION,       #counter, Throttling duration due to power constraints (in us).
              DCGM_FI_DEV_THERMAL_VIOLATION,     #counter, Throttling duration due to thermal constraints (in us).
              DCGM_FI_DEV_SYNC_BOOST_VIOLATION,  #counter, Throttling duration due to sync-boost constraints (in us).
              DCGM_FI_DEV_BOARD_LIMIT_VIOLATION, #counter, Throttling duration due to board limit constraints (in us).
              DCGM_FI_DEV_LOW_UTIL_VIOLATION,    #counter, Throttling duration due to low utilization (in us).
              DCGM_FI_DEV_RELIABILITY_VIOLATION, #counter, Throttling duration due to reliability constraints (in us).

              # Memory usage
              DCGM_FI_DEV_FB_FREE,  #gauge, Framebuffer memory free (in MiB).
              DCGM_FI_DEV_FB_USED,  #gauge, Framebuffer memory used (in MiB).
              DCGM_FI_DEV_FB_TOTAL, #gauge, Framebuffer memory total (in MiB).

              # ECC
              # DCGM_FI_DEV_ECC_SBE_VOL_TOTAL, #counter, Total number of single-bit volatile ECC errors.
              # DCGM_FI_DEV_ECC_DBE_VOL_TOTAL, #counter, Total number of double-bit volatile ECC errors.
              # DCGM_FI_DEV_ECC_SBE_AGG_TOTAL, #counter, Total number of single-bit persistent ECC errors.
              # DCGM_FI_DEV_ECC_DBE_AGG_TOTAL, #counter, Total number of double-bit persistent ECC errors.

              # Retired pages
              DCGM_FI_DEV_RETIRED_SBE,     #counter, Total number of retired pages due to single-bit errors.
              DCGM_FI_DEV_RETIRED_DBE,     #counter, Total number of retired pages due to double-bit errors.
              # DCGM_FI_DEV_RETIRED_PENDING, #counter, Total number of pages pending retirement.
              
              # NVLink
              # DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_TOTAL, #counter, Total number of NVLink flow-control CRC errors.
              # DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_TOTAL, #counter, Total number of NVLink data CRC errors.
              # DCGM_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_TOTAL,   #counter, Total number of NVLink retries.
              # DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_TOTAL, #counter, Total number of NVLink recovery errors.
              DCGM_FI_DEV_NVLINK_BANDWIDTH_TOTAL,            #counter, Total number of NVLink bandwidth counters for all lanes.
              # DCGM_FI_DEV_NVLINK_BANDWIDTH_L0,               #counter, The number of bytes of active NVLink rx or tx data including both header and payload.
              # DCGM_FI_DEV_RETIRED_PENDING, #counter, Total number of pages pending retirement.

              # Fan status
              DCGM_FI_DEV_FAN_SPEED, #counter, GPU Fan Speed (in %)

              # Remapped rows
              DCGM_FI_DEV_UNCORRECTABLE_REMAPPED_ROWS, #counter, Number of remapped rows for uncorrectable errors
              DCGM_FI_DEV_CORRECTABLE_REMAPPED_ROWS,   #counter, Number of remapped rows for correctable errors
              DCGM_FI_DEV_ROW_REMAP_FAILURE,           #gauge,   Whether remapping of rows has failed

              # Static configuration information. These appear as labels on the other metrics
              # DCGM_FI_DRIVER_VERSION,        #label, Driver Version
              # DCGM_FI_NVML_VERSION,          #label, NVML Version
              # DCGM_FI_DEV_BRAND,             #label, Device Brand
              DCGM_FI_DEV_SERIAL,            #label, Device Serial Number
              # DCGM_FI_DEV_OEM_INFOROM_VER,   #label, OEM inforom version
              # DCGM_FI_DEV_ECC_INFOROM_VER,   #label, ECC inforom version
              # DCGM_FI_DEV_POWER_INFOROM_VER, #label, Power management object inforom version
              # DCGM_FI_DEV_INFOROM_IMAGE_VER, #label, Inforom image version
              # DCGM_FI_DEV_VBIOS_VERSION,     #label, VBIOS version of the device
            ]
          low:
            scrape_interval_secs: 300
            fields: [
               # Clocks
              DCGM_FI_DEV_SM_CLOCK,      #gauge, SM clock frequency (in MHz).
              DCGM_FI_DEV_MEM_CLOCK,     #gauge, Memory clock frequency (in MHz).
              DCGM_FI_DEV_MAX_SM_CLOCK,  #gauge, Max SM clock frequency (in MHz).
              DCGM_FI_DEV_MAX_MEM_CLOCK, #gauge, Max Memory clock frequency (in MHz).
              DCGM_FI_DEV_APP_SM_CLOCK,  #gauge, App SM clock frequency (in MHz).
              DCGM_FI_DEV_APP_MEM_CLOCK, #gauge, App Memory clock frequency (in MHz).
              # P status
              DCGM_FI_DEV_PSTATE,        # gauge, Performance state (P-State) 0-15. 0=highest
            ]
```

label逻辑错误：

degm exporter对于标签类的指标是直接写到tags的

但现在是作为了一个指标
```
{"name":"DCGM_FI_DEV_SERIAL","tags":{"DCGM_FI_DEV_SERIAL":"1561520003915","cluster":"tianqing_a100","gpu_id":"3","group":"mid","node":"nh-dc-nm130-c03-9u-gpu-4"},"timestamp":"2025-06-24T04:32:48.952981320Z","kind":"absolute","gauge":{"value":0.0}}
```

expect:

所有指标都带有"DCGM_FI_DEV_SERIAL":"1561520003915"的tags

### 软件版本

-

### 严重程度

低（不影响使用）

### 重现步骤

-

### Configuration

```text

```

### Version

-

### Debug Output

```text

```
