### ISSUE TITLE
Developing a PCIE collector

### ISSUE THREAD

**Issue by Wangyiwei-So** [zjnc-tech/vector#5]
### A note for the community

开发一个pcie collector(source)，采集pcie配置、带宽指标

**Comment by Wangyiwei-So** [comment]
可以直接通过配置的方式来采集
```yaml
sources:
  pci_info:
    type: "exec"
    command: [ "lspci", "-nn" ]
    mode: "scheduled"
    scheduled:
      exec_interval_secs: 60
transforms:
  parse_pci:
    type: "remap"
    inputs: 
     - "pci_info"
    source: |
      . = parse_regex!(.message, r'^(?P<bus_id>[0-9a-f:\.]+)\s+(?P<device_type>.*?)\s+\[(?P<type_code>[0-9a-f]{4})\]:\s+(?P<vendor>.*?)\s+(?P<device_name>.*?)\s+\[(?P<vendor_id>[0-9a-f]{4}):(?P<device_id>[0-9a-f]{4})\]\s+\(rev\s+(?P<revision>[0-9a-f]{2})\)')
      .timestamp = now()
sinks:
  clickhouse:
    type: "clickhouse"
    inputs: 
    - "parse_pci"
    compression: zstd
    auth:
      password: zjlab@2024
      user: admin
      strategy: basic
    database: "graphite"
    endpoint: "http://pre-isg.fed.clickhouse.zhejianglab.org:80"
    format: json_each_row
    table: "pci_device_test"
    skip_unknown_fields: true
    batch:
      max_events: 100
      timeout_secs: 2
```
